import { useState, useEffect } from "react";
import { FIELDS } from "../config/fields.js";
import { SEG_COLORS } from "../config/taxonomy.js";
import { marginOf, fmtDateTime } from "../lib/util.js";
import { buildSku, nextStyleNo, isFolderLink } from "../lib/sku.js";
import { draftCopy } from "../lib/ai.js";
import SkuTicket from "./SkuTicket.jsx";

export default function EditView({ product, setProduct, products, brands, categories, materials, colours, skuConfig, ctx, aiSettings, othersEditing = [], requiredFields = [], onSave, onCancel, openStudio, say }) {
  const [busy, setBusy] = useState(false);
  const [dept, setDept] = useState(() => categories.find((c) => c.code === product.categoryCode)?.dept || "Bags");
  const set = (k, v) => setProduct((p) => ({ ...p, [k]: v }));
  const brand = brands.find((b) => b.id === product.brandId);
  const depts = [...new Set(categories.map((c) => c.dept))];

  useEffect(() => { if (product.brandId && product.categoryCode && !product.styleNo) set("styleNo", nextStyleNo(products, product.brandId, product.categoryCode, skuConfig.styleDigits)); }, [product.brandId, product.categoryCode]);
  const built = buildSku(product, ctx);
  useEffect(() => { if (!product.skuLocked) set("sku", built.sku); }, [built.sku, product.skuLocked]);

  const applyBrandDefaults = (id) => { const b = brands.find((x) => x.id === id); setProduct((p) => ({ ...p, brandId: id, hsn: p.hsn || b?.hsn || "", gst: p.gst || b?.gst || "", warranty: p.warranty || b?.warranty || "", care: p.care || b?.care || "", styleNo: "" })); };
  const dup = products.some((p) => p.id !== product.id && p.sku && p.sku === product.sku);
  const bumpStyle = () => set("styleNo", nextStyleNo(products, product.brandId, product.categoryCode, skuConfig.styleDigits));

  const writeCopy = async () => {
    setBusy(true);
    try {
      const j = await draftCopy(aiSettings, `brand ${brand?.name || ""}; name ${product.name}; category ${categories.find((c) => c.code === product.categoryCode)?.name || ""}; contents ${product.contents}; colour ${product.colour}; pattern ${product.pattern}; material ${product.material}; compartments ${product.compartment}; audience ${product.ageGroup}; water ${product.water}`);
      setProduct((p) => ({ ...p, about: j.about || p.about, benefits: j.benefits || p.benefits, f1: j.f1 || p.f1, f2: j.f2 || p.f2, f3: j.f3 || p.f3 }));
      say("Copy drafted — review before saving");
    } catch (e) { say("Could not draft copy: " + e.message); }
    setBusy(false);
  };

  const input = (f) => {
    if (f.type === "brand") return <select value={product.brandId} onChange={(e) => applyBrandDefaults(e.target.value)}>{brands.map((b) => <option key={b.id} value={b.id}>{b.name} ({b.code})</option>)}</select>;
    if (f.type === "sku") return <div className="row"><input className="mono" value={product.sku} disabled={!product.skuLocked} onChange={(e) => set("sku", e.target.value.toUpperCase())} /><label className="check" style={{ whiteSpace: "nowrap" }}><input type="checkbox" checked={product.skuLocked} onChange={(e) => set("skuLocked", e.target.checked)} /> manual</label></div>;
    if (f.type === "date") return <input value={fmtDateTime(product[f.key])} disabled placeholder="set automatically" />;
    if (f.key === "skuSource") return <input value={product.skuLocked ? "manual / imported (typed, not generated)" : "system-generated by the rule"} disabled />;
    if (f.type === "computed") return <input value={marginOf(product) ? marginOf(product) + " %" : ""} disabled placeholder="auto (selling − landing) ÷ selling" />;
    if (f.type === "select") return <select value={product[f.key]} onChange={(e) => set(f.key, e.target.value)}>{f.options.map((o) => <option key={o}>{o}</option>)}</select>;
    if (f.type === "textarea") return <textarea value={product[f.key]} onChange={(e) => set(f.key, e.target.value)} />;
    if (f.key === "colour") return <><input list="colourlist" value={product.colour} onChange={(e) => set("colour", e.target.value)} /><datalist id="colourlist">{colours.map((c) => <option key={c.name} value={c.name} />)}</datalist></>;
    if (f.key === "material") return <><input list="matlist" value={product.material} onChange={(e) => set("material", e.target.value)} /><datalist id="matlist">{materials.map((m) => <option key={m.code} value={m.name} />)}</datalist></>;
    if (f.key === "videoUrl") { const v = product.videoUrl || ""; return <div className="row" style={{ flexWrap: "nowrap" }}><input value={v} onChange={(e) => set("videoUrl", e.target.value)} placeholder="YouTube (unlisted) / Drive / .mp4 link — optional" />{v && <a className="btn small" href={v} target="_blank" rel="noreferrer">▶ open</a>}</div>; }
    if (f.type === "url") { const v = product[f.key] || ""; return <div className="row" style={{ flexWrap: "nowrap" }}><input value={v} onChange={(e) => set(f.key, e.target.value)} placeholder={f.key === "imageUrl" ? "main image https://…" : "https://… (optional)"} />{v && !isFolderLink(v) && <a href={v} target="_blank" rel="noreferrer" title="open"><img src={v.includes("drive.google.com/file/d/") ? "https://drive.google.com/thumbnail?id=" + (v.match(/\/d\/([\w-]+)/) || [])[1] : v} alt="" style={{ width: 38, height: 38, objectFit: "cover", borderRadius: 6, border: "1px solid var(--line)" }} onError={(e) => { e.currentTarget.style.display = "none"; }} /></a>}{isFolderLink(v) && <span className="note" style={{ color: "var(--ox)", whiteSpace: "nowrap" }}>folder link ⚠</span>}</div>; }
    return <input type={f.type === "number" ? "number" : "text"} step={f.step} value={product[f.key]} onChange={(e) => set(f.key, e.target.value)} />;
  };
  const skuDot = (f) => <>{f.sku && <span style={{ color: SEG_COLORS[f.sku] }}> ●</span>}{requiredFields.includes(f.key) && String(product[f.key] ?? "").trim() === "" && <span style={{ color: "var(--ox)" }} title="required for a complete listing"> · missing</span>}</>;

  return (
    <div className="grid2" style={{ gridTemplateColumns: "1fr 360px", alignItems: "start" }}>
      <div className="panel">
        <h2 style={{ fontSize: 20, marginBottom: 14 }}>Product details</h2>
        {product.sku && othersEditing.includes(product.sku) && <div className="panel" style={{ borderColor: "#E6B8B8", background: "#FBEAEA", marginBottom: 12, padding: 10 }}>⚠ Someone else is editing <b className="mono">{product.sku}</b> right now. Coordinate before saving — the last save wins.</div>}
        <div className="grid4">
          <div className="field"><label>Product name (internal)</label><input value={product.name} onChange={(e) => set("name", e.target.value)} placeholder="e.g. Croco shoulder bag" /></div>
          <div className="field"><label>Department</label><select value={dept} onChange={(e) => { setDept(e.target.value); set("categoryCode", ""); }}>{depts.map((d) => <option key={d}>{d}</option>)}</select></div>
          <div className="field"><label>Category <span style={{ color: SEG_COLORS.category }}>●</span></label><select value={product.categoryCode} onChange={(e) => set("categoryCode", e.target.value)}><option value="">— pick —</option>{categories.filter((c) => c.dept === dept).map((c) => <option key={c.code} value={c.code}>{c.name} ({c.code})</option>)}</select></div>
          <div className="field"><label>Style no. <span style={{ color: SEG_COLORS.style }}>●</span></label><input className="mono" value={product.styleNo} onChange={(e) => set("styleNo", e.target.value.replace(/\D/g, ""))} placeholder="auto" /></div>
        </div>
        {[...new Set(FIELDS.filter((f) => f.type !== "textarea").map((f) => f.grp))].map((g) => (
          <div key={g}><label style={{ marginTop: 6, color: "var(--olive)" }}>{g}</label><div className="grid3">
            {FIELDS.filter((f) => f.grp === g && f.type !== "textarea").map((f) => <div className="field" key={f.key}><label>{f.label}{skuDot(f)}</label>{input(f)}</div>)}
          </div></div>))}
        <div className="row" style={{ justifyContent: "space-between", margin: "6px 0 10px" }}><h3 style={{ fontSize: 16 }}>Listing copy</h3><button className="btn small" disabled={busy} onClick={writeCopy}>{busy ? "Drafting…" : "✦ Draft with AI"}</button></div>
        {FIELDS.filter((f) => f.type === "textarea").map((f) => <div className="field" key={f.key}><label>{f.label}</label>{input(f)}</div>)}
        <div className="row" style={{ marginTop: 10 }}>
          <button className="btn primary" disabled={!product.sku || dup} onClick={() => onSave(product)}>Save product</button>
          <button className="btn" onClick={() => openStudio(product)}>Open in image studio</button>
          <button className="btn" onClick={onCancel}>Cancel</button>
          {dup && <span className="note" style={{ color: "var(--ox)" }}>SKU already exists. {product.skuLocked ? "Change it above." : <>Change colour, or <button className="btn small" onClick={bumpStyle}>use next style no.</button></>}</span>}
        </div>
      </div>
      <div style={{ position: "sticky", top: 84 }}>
        <SkuTicket parts={built.parts} sku={built.sku} separator={skuConfig.separator} showMeaning />
        <div className="note" style={{ marginTop: 10 }}>Dots (●) mark fields that feed the SKU. New colour names get a permanent code that never clashes with an existing one. Every SKU must be unique — saving is blocked otherwise.</div>
        {product.thumb && <img src={product.thumb} alt="" style={{ width: "100%", borderRadius: 12, marginTop: 12, border: "1px solid var(--line)" }} />}
      </div>
    </div>
  );
}
